//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCMMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppIsStart {
            get {
                return ((bool)(this["AppIsStart"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.151;database=NCMMS;uid=NCMMS;pwd=NCMMS;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MPIsSingleColumn {
            get {
                return ((bool)(this["MPIsSingleColumn"]));
            }
            set {
                this["MPIsSingleColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1.1.1.1</string>
  <string>2.2.2.2</string>
  <string>3.3.3.3</string>
  <string>4.4.4.4</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MPStrIPList1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MPStrIPList1"]));
            }
            set {
                this["MPStrIPList1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>11.11.11.11</string>
  <string>22.22.22.22</string>
  <string>33.33.33.33</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MPStrIPList2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MPStrIPList2"]));
            }
            set {
                this["MPStrIPList2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int MPTimeOut {
            get {
                return ((int)(this["MPTimeOut"]));
            }
            set {
                this["MPTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int MPDataSize {
            get {
                return ((int)(this["MPDataSize"]));
            }
            set {
                this["MPDataSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int MPTTL {
            get {
                return ((int)(this["MPTTL"]));
            }
            set {
                this["MPTTL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MPNumber {
            get {
                return ((int)(this["MPNumber"]));
            }
            set {
                this["MPNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MPInterval {
            get {
                return ((int)(this["MPInterval"]));
            }
            set {
                this["MPInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MPIsRecord {
            get {
                return ((bool)(this["MPIsRecord"]));
            }
            set {
                this["MPIsRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MPIsAlarm {
            get {
                return ((bool)(this["MPIsAlarm"]));
            }
            set {
                this["MPIsAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MPAlarmFileUrl {
            get {
                return ((string)(this["MPAlarmFileUrl"]));
            }
            set {
                this["MPAlarmFileUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackgroundPicUrl {
            get {
                return ((string)(this["BackgroundPicUrl"]));
            }
            set {
                this["BackgroundPicUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string WindowBannerColor {
            get {
                return ((string)(this["WindowBannerColor"]));
            }
            set {
                this["WindowBannerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("public")]
        public string SNMP_Community {
            get {
                return ((string)(this["SNMP_Community"]));
            }
            set {
                this["SNMP_Community"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("161")]
        public int SNMP_Port {
            get {
                return ((int)(this["SNMP_Port"]));
            }
            set {
                this["SNMP_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162")]
        public int SNMP_Trap_Port {
            get {
                return ((int)(this["SNMP_Trap_Port"]));
            }
            set {
                this["SNMP_Trap_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int SNMP_Timeout {
            get {
                return ((int)(this["SNMP_Timeout"]));
            }
            set {
                this["SNMP_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SNMP_Retry {
            get {
                return ((int)(this["SNMP_Retry"]));
            }
            set {
                this["SNMP_Retry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SNMP_CheckSrcFlag {
            get {
                return ((bool)(this["SNMP_CheckSrcFlag"]));
            }
            set {
                this["SNMP_CheckSrcFlag"] = value;
            }
        }
    }
}
